---
deployment:
 tasks:
 - export DEPLOYPATH=$HOME/public_html
 - export SOURCEPATH=public_html/
 - $HOME/bin/rsync -a --exclude={'app/devices'} $SOURCEPATH $DEPLOYPATH    # Don't overwrite anything in the apps/devices folder - these come from other repos